# Site Author
author:
  name             : "Guodong Du (杜国东)"
  avatar           : "images/android-chrome-512x512.png"
  bio              : "Lorem ipsum College"
  location         : "Shenzhen, China"
  googlescholar    : "https://scholar.google.com/citations?user=YOUR_GOOGLE_SCHOLAR_ID"
  email            : "Lorem@ipsum.com"
  researchgate     :  # e.g., "https://www.researchgate.net/profile/yourprofile"
  uri              :
  facebook         :
  foursquare       :
  github           : # e.g., "github username"
